# Generated by Django 2.1.5 on 2019-02-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcemanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='size',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
