# Generated by Django 2.1.5 on 2019-02-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcemanage', '0002_car_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='carord',
            name='sta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metorder',
            name='sta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
